// Generated by Grafana k6 Studio (1.13.1) on 2026-06-05T17:53:34.311Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fwidgets%2Fslide-2%2Fbanner-two.jpg&w=2400&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fwidgets%2Fslide-1%2Fbanner-one.jpg&w=2400&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/assets/frontstore-vendor/client/dfc334de564d120d3e79.js`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F1367%2F5867%2Fthermos-yellow.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/assets/frontStore/homepage/client/dfc334de564d120d3e79.js`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F6080%2F3993%2Fthermos-black.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F8588%2F5302%2Fthermos-white.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F9698%2F2255%2Fvase-green.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/favicon.ico`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 404": (r) => r.status === 200 });
  });
  sleep(1);
  group("Click on Shop Now button", function () {
    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        referer: `https://tvn-sut.info/`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/accessories`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F5974%2F6129%2Fvase-black.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F8732%2F5650%2Fvase-white.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/assets/frontStore/categoryView/client/dfc334de564d120d3e79.js`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F1651%2F3721%2Fbowl-yellow.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F7513%2F4442%2Fbowl-black.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F5744%2F4438%2Fbowl-white.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F7248%2F4801%2Fpen-holder-yellow.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F6306%2F6213%2Fpen-holder-black.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F6664%2F7196%2Fpen-holder-white.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F4375%2F1641%2Fcup-yellow.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F1705%2F6331%2Fcup-black.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F1369%2F4111%2Fcup-white.jpg&w=750&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("Load product details", function () {
    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        referer: `https://tvn-sut.info/accessories`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/accessories/modern-ceramic-vase-black`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        referer: `https://tvn-sut.info/accessories/modern-ceramic-vase-black`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/images?src=%2Fassets%2Fcatalog%2F5974%2F6129%2Fvase-black.jpg&w=1200&q=75`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        referer: `https://tvn-sut.info/accessories/modern-ceramic-vase-black`,
      },
      cookies: {},
    };

    url = http.url`https://tvn-sut.info/assets/frontStore/productView/client/dfc334de564d120d3e79.js`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
}
